import z from 'zod'

export interface ProductResponseTypes {
  id: string
  user_id: string
  name: string
  slug: string
  description: string
  price_cent: number
  status: string
  is_featured: boolean
  included: string[]
  tags: string[] // UUIDs
  categories: string[] // UUIDs
  images: string[]
  asset_url?: string[]
}

export type CategoryTypes = {
  id: string
  name: string
  slug: string
}

export interface TagsTypes {
  id: string
  name: string
}

/**
 * Product payload sent to the backend
 */
export interface ProductTypes {
  id?: string // Made optional (generated by backend/DB)
  user_id?: string | null // Made optional (assigned by backend/auth)
  name: string
  slug?: string | null // Made optional (generated from name)
  description: string
  price_cent: number
  included: string[]
  status?: string | null // Made optional (defaulted by backend)
  is_featured?: boolean // Made optional (defaulted by backend)

  tag_ids?: string[]
  categories_ids?: string[]
  images?: string[]
  asset_url?: string
}

const MAX_FILE_SIZE_ASSET = 10 * 1024 * 1024
const MAX_FILE_SIZE_IMAGES = 10 * 1024 * 1024

export const fileSchema = z
  .array(
    z.instanceof(File).refine((file) => file.size <= MAX_FILE_SIZE_IMAGES, {
      message: 'Each file must be less than 5MB',
    }),
  )
  .min(1, { message: 'At least one file is required' })
  .max(10, { message: 'Maximum 10 files allowed' })

export const assetSchema = z
  .instanceof(File, { message: 'Please select a file' })
  .refine((file) => file.size <= MAX_FILE_SIZE_ASSET, {
    message: 'File size must be less than 10MB',
  })
/**
 * Product form schema – validates the input before sending
 */
export const ProductSchema = z.object({
  name: z.string().min(3, { message: 'Name is required' }),
  description: z.string().min(3, { message: 'Description is required' }),
  price_cents: z.string().regex(/^\d+(\.\d{1,2})?$/, {
    message: 'Price must be a valid dollar amount (e.g., 20.00)',
  }),
  tags: z.array(z.uuid()).min(1, {
    message: 'At least one tag is required',
  }),
  categories: z.array(z.uuid()).min(1, {
    message: 'At least one category is required',
  }),
  included: z.array(z.string()).min(1, {
    message: 'At least one included item is required',
  }),
  images: fileSchema,
  asset_url: assetSchema,
})

export interface GetProductsParams {
  page?: number
  limit?: number
}

export type ProductFormTypes = z.infer<typeof ProductSchema>
//
// export interface ProductResponseTypes {
//   id: string // required, e.g., "18b77502-b151-490f-9e06-b89fa430ddd9"
//   owner_id: string // required, e.g., "66d35dff-3750-49f9-8fc1-f947f45d0940"
//   name: string
//   slug: string
//   description: string
//   price_cents: number // e.g., 9540 → $95.40
//   status: 'DRAFT' | 'PUBLISHED' | 'ARCHIVED' // adjust as needed
//   is_featured: boolean
//   included: string[]
//   tags: string[]
//   categories: string[] // e.g., "MOCKUPS", "PLUGINS", etc.
//   images: string[] // URLs
//   assets: string[] // URLs or file paths
// }
