/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TemplatesIndexRouteImport } from './routes/templates/index'
import { Route as MockupsIndexRouteImport } from './routes/mockups/index'
import { Route as GraphicsIndexRouteImport } from './routes/graphics/index'
import { Route as TemplatesItemIdRouteImport } from './routes/templates/$itemId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesIndexRoute = TemplatesIndexRouteImport.update({
  id: '/templates/',
  path: '/templates/',
  getParentRoute: () => rootRouteImport,
} as any)
const MockupsIndexRoute = MockupsIndexRouteImport.update({
  id: '/mockups/',
  path: '/mockups/',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphicsIndexRoute = GraphicsIndexRouteImport.update({
  id: '/graphics/',
  path: '/graphics/',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesItemIdRoute = TemplatesItemIdRouteImport.update({
  id: '/templates/$itemId',
  path: '/templates/$itemId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/templates/$itemId': typeof TemplatesItemIdRoute
  '/graphics/': typeof GraphicsIndexRoute
  '/mockups/': typeof MockupsIndexRoute
  '/templates/': typeof TemplatesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/templates/$itemId': typeof TemplatesItemIdRoute
  '/graphics': typeof GraphicsIndexRoute
  '/mockups': typeof MockupsIndexRoute
  '/templates': typeof TemplatesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/templates/$itemId': typeof TemplatesItemIdRoute
  '/graphics/': typeof GraphicsIndexRoute
  '/mockups/': typeof MockupsIndexRoute
  '/templates/': typeof TemplatesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/templates/$itemId'
    | '/graphics/'
    | '/mockups/'
    | '/templates/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/templates/$itemId' | '/graphics' | '/mockups' | '/templates'
  id:
    | '__root__'
    | '/'
    | '/templates/$itemId'
    | '/graphics/'
    | '/mockups/'
    | '/templates/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TemplatesItemIdRoute: typeof TemplatesItemIdRoute
  GraphicsIndexRoute: typeof GraphicsIndexRoute
  MockupsIndexRoute: typeof MockupsIndexRoute
  TemplatesIndexRoute: typeof TemplatesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/': {
      id: '/templates/'
      path: '/templates'
      fullPath: '/templates/'
      preLoaderRoute: typeof TemplatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mockups/': {
      id: '/mockups/'
      path: '/mockups'
      fullPath: '/mockups/'
      preLoaderRoute: typeof MockupsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graphics/': {
      id: '/graphics/'
      path: '/graphics'
      fullPath: '/graphics/'
      preLoaderRoute: typeof GraphicsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/$itemId': {
      id: '/templates/$itemId'
      path: '/templates/$itemId'
      fullPath: '/templates/$itemId'
      preLoaderRoute: typeof TemplatesItemIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TemplatesItemIdRoute: TemplatesItemIdRoute,
  GraphicsIndexRoute: GraphicsIndexRoute,
  MockupsIndexRoute: MockupsIndexRoute,
  TemplatesIndexRoute: TemplatesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
