/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TermsIndexRouteImport } from './routes/terms/index'
import { Route as TemplatesIndexRouteImport } from './routes/templates/index'
import { Route as SupportIndexRouteImport } from './routes/support/index'
import { Route as PrivacyIndexRouteImport } from './routes/privacy/index'
import { Route as MockupsIndexRouteImport } from './routes/mockups/index'
import { Route as MagazinesIndexRouteImport } from './routes/magazines/index'
import { Route as LicenseIndexRouteImport } from './routes/license/index'
import { Route as GraphicsIndexRouteImport } from './routes/graphics/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as ContactIndexRouteImport } from './routes/contact/index'
import { Route as AboutIndexRouteImport } from './routes/about/index'
import { Route as TemplatesSlugRouteImport } from './routes/templates/$slug'
import { Route as MockupsSlugRouteImport } from './routes/mockups/$slug'
import { Route as MagazinesSlugRouteImport } from './routes/magazines/$slug'
import { Route as GraphicsSlugRouteImport } from './routes/graphics/$slug'
import { Route as ApiGraphqlRouteImport } from './routes/api/graphql'
import { Route as DashboardSettingsIndexRouteImport } from './routes/dashboard/settings/index'
import { Route as DashboardPurchase_historyIndexRouteImport } from './routes/dashboard/purchase_history/index'
import { Route as DashboardProfileIndexRouteImport } from './routes/dashboard/profile/index'
import { Route as DashboardProductsIndexRouteImport } from './routes/dashboard/products/index'
import { Route as DashboardFoldersIndexRouteImport } from './routes/dashboard/folders/index'
import { Route as authSigninIndexRouteImport } from './routes/(auth)/signin/index'
import { Route as authRegisterIndexRouteImport } from './routes/(auth)/register/index'
import { Route as ApiAuthRegisterRouteImport } from './routes/api/auth/register'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth/logout'
import { Route as ApiAuthLoginRouteImport } from './routes/api/auth/login'

const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsIndexRoute = TermsIndexRouteImport.update({
  id: '/terms/',
  path: '/terms/',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesIndexRoute = TemplatesIndexRouteImport.update({
  id: '/templates/',
  path: '/templates/',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportIndexRoute = SupportIndexRouteImport.update({
  id: '/support/',
  path: '/support/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyIndexRoute = PrivacyIndexRouteImport.update({
  id: '/privacy/',
  path: '/privacy/',
  getParentRoute: () => rootRouteImport,
} as any)
const MockupsIndexRoute = MockupsIndexRouteImport.update({
  id: '/mockups/',
  path: '/mockups/',
  getParentRoute: () => rootRouteImport,
} as any)
const MagazinesIndexRoute = MagazinesIndexRouteImport.update({
  id: '/magazines/',
  path: '/magazines/',
  getParentRoute: () => rootRouteImport,
} as any)
const LicenseIndexRoute = LicenseIndexRouteImport.update({
  id: '/license/',
  path: '/license/',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphicsIndexRoute = GraphicsIndexRouteImport.update({
  id: '/graphics/',
  path: '/graphics/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const ContactIndexRoute = ContactIndexRouteImport.update({
  id: '/contact/',
  path: '/contact/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesSlugRoute = TemplatesSlugRouteImport.update({
  id: '/templates/$slug',
  path: '/templates/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MockupsSlugRoute = MockupsSlugRouteImport.update({
  id: '/mockups/$slug',
  path: '/mockups/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MagazinesSlugRoute = MagazinesSlugRouteImport.update({
  id: '/magazines/$slug',
  path: '/magazines/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphicsSlugRoute = GraphicsSlugRouteImport.update({
  id: '/graphics/$slug',
  path: '/graphics/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGraphqlRoute = ApiGraphqlRouteImport.update({
  id: '/api/graphql',
  path: '/api/graphql',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSettingsIndexRoute = DashboardSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardPurchase_historyIndexRoute =
  DashboardPurchase_historyIndexRouteImport.update({
    id: '/purchase_history/',
    path: '/purchase_history/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardProfileIndexRoute = DashboardProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardProductsIndexRoute = DashboardProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardFoldersIndexRoute = DashboardFoldersIndexRouteImport.update({
  id: '/folders/',
  path: '/folders/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const authSigninIndexRoute = authSigninIndexRouteImport.update({
  id: '/(auth)/signin/',
  path: '/signin/',
  getParentRoute: () => rootRouteImport,
} as any)
const authRegisterIndexRoute = authRegisterIndexRouteImport.update({
  id: '/(auth)/register/',
  path: '/register/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthRegisterRoute = ApiAuthRegisterRouteImport.update({
  id: '/api/auth/register',
  path: '/api/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/api/graphql': typeof ApiGraphqlRoute
  '/graphics/$slug': typeof GraphicsSlugRoute
  '/magazines/$slug': typeof MagazinesSlugRoute
  '/mockups/$slug': typeof MockupsSlugRoute
  '/templates/$slug': typeof TemplatesSlugRoute
  '/about/': typeof AboutIndexRoute
  '/contact/': typeof ContactIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/graphics/': typeof GraphicsIndexRoute
  '/license/': typeof LicenseIndexRoute
  '/magazines/': typeof MagazinesIndexRoute
  '/mockups/': typeof MockupsIndexRoute
  '/privacy/': typeof PrivacyIndexRoute
  '/support/': typeof SupportIndexRoute
  '/templates/': typeof TemplatesIndexRoute
  '/terms/': typeof TermsIndexRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/register': typeof ApiAuthRegisterRoute
  '/register/': typeof authRegisterIndexRoute
  '/signin/': typeof authSigninIndexRoute
  '/dashboard/folders/': typeof DashboardFoldersIndexRoute
  '/dashboard/products/': typeof DashboardProductsIndexRoute
  '/dashboard/profile/': typeof DashboardProfileIndexRoute
  '/dashboard/purchase_history/': typeof DashboardPurchase_historyIndexRoute
  '/dashboard/settings/': typeof DashboardSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/graphql': typeof ApiGraphqlRoute
  '/graphics/$slug': typeof GraphicsSlugRoute
  '/magazines/$slug': typeof MagazinesSlugRoute
  '/mockups/$slug': typeof MockupsSlugRoute
  '/templates/$slug': typeof TemplatesSlugRoute
  '/about': typeof AboutIndexRoute
  '/contact': typeof ContactIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/graphics': typeof GraphicsIndexRoute
  '/license': typeof LicenseIndexRoute
  '/magazines': typeof MagazinesIndexRoute
  '/mockups': typeof MockupsIndexRoute
  '/privacy': typeof PrivacyIndexRoute
  '/support': typeof SupportIndexRoute
  '/templates': typeof TemplatesIndexRoute
  '/terms': typeof TermsIndexRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/register': typeof ApiAuthRegisterRoute
  '/register': typeof authRegisterIndexRoute
  '/signin': typeof authSigninIndexRoute
  '/dashboard/folders': typeof DashboardFoldersIndexRoute
  '/dashboard/products': typeof DashboardProductsIndexRoute
  '/dashboard/profile': typeof DashboardProfileIndexRoute
  '/dashboard/purchase_history': typeof DashboardPurchase_historyIndexRoute
  '/dashboard/settings': typeof DashboardSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/api/graphql': typeof ApiGraphqlRoute
  '/graphics/$slug': typeof GraphicsSlugRoute
  '/magazines/$slug': typeof MagazinesSlugRoute
  '/mockups/$slug': typeof MockupsSlugRoute
  '/templates/$slug': typeof TemplatesSlugRoute
  '/about/': typeof AboutIndexRoute
  '/contact/': typeof ContactIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/graphics/': typeof GraphicsIndexRoute
  '/license/': typeof LicenseIndexRoute
  '/magazines/': typeof MagazinesIndexRoute
  '/mockups/': typeof MockupsIndexRoute
  '/privacy/': typeof PrivacyIndexRoute
  '/support/': typeof SupportIndexRoute
  '/templates/': typeof TemplatesIndexRoute
  '/terms/': typeof TermsIndexRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/register': typeof ApiAuthRegisterRoute
  '/(auth)/register/': typeof authRegisterIndexRoute
  '/(auth)/signin/': typeof authSigninIndexRoute
  '/dashboard/folders/': typeof DashboardFoldersIndexRoute
  '/dashboard/products/': typeof DashboardProductsIndexRoute
  '/dashboard/profile/': typeof DashboardProfileIndexRoute
  '/dashboard/purchase_history/': typeof DashboardPurchase_historyIndexRoute
  '/dashboard/settings/': typeof DashboardSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/api/graphql'
    | '/graphics/$slug'
    | '/magazines/$slug'
    | '/mockups/$slug'
    | '/templates/$slug'
    | '/about/'
    | '/contact/'
    | '/dashboard/'
    | '/graphics/'
    | '/license/'
    | '/magazines/'
    | '/mockups/'
    | '/privacy/'
    | '/support/'
    | '/templates/'
    | '/terms/'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/register'
    | '/register/'
    | '/signin/'
    | '/dashboard/folders/'
    | '/dashboard/products/'
    | '/dashboard/profile/'
    | '/dashboard/purchase_history/'
    | '/dashboard/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/graphql'
    | '/graphics/$slug'
    | '/magazines/$slug'
    | '/mockups/$slug'
    | '/templates/$slug'
    | '/about'
    | '/contact'
    | '/dashboard'
    | '/graphics'
    | '/license'
    | '/magazines'
    | '/mockups'
    | '/privacy'
    | '/support'
    | '/templates'
    | '/terms'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/register'
    | '/register'
    | '/signin'
    | '/dashboard/folders'
    | '/dashboard/products'
    | '/dashboard/profile'
    | '/dashboard/purchase_history'
    | '/dashboard/settings'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/api/graphql'
    | '/graphics/$slug'
    | '/magazines/$slug'
    | '/mockups/$slug'
    | '/templates/$slug'
    | '/about/'
    | '/contact/'
    | '/dashboard/'
    | '/graphics/'
    | '/license/'
    | '/magazines/'
    | '/mockups/'
    | '/privacy/'
    | '/support/'
    | '/templates/'
    | '/terms/'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/register'
    | '/(auth)/register/'
    | '/(auth)/signin/'
    | '/dashboard/folders/'
    | '/dashboard/products/'
    | '/dashboard/profile/'
    | '/dashboard/purchase_history/'
    | '/dashboard/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  ApiGraphqlRoute: typeof ApiGraphqlRoute
  GraphicsSlugRoute: typeof GraphicsSlugRoute
  MagazinesSlugRoute: typeof MagazinesSlugRoute
  MockupsSlugRoute: typeof MockupsSlugRoute
  TemplatesSlugRoute: typeof TemplatesSlugRoute
  AboutIndexRoute: typeof AboutIndexRoute
  ContactIndexRoute: typeof ContactIndexRoute
  GraphicsIndexRoute: typeof GraphicsIndexRoute
  LicenseIndexRoute: typeof LicenseIndexRoute
  MagazinesIndexRoute: typeof MagazinesIndexRoute
  MockupsIndexRoute: typeof MockupsIndexRoute
  PrivacyIndexRoute: typeof PrivacyIndexRoute
  SupportIndexRoute: typeof SupportIndexRoute
  TemplatesIndexRoute: typeof TemplatesIndexRoute
  TermsIndexRoute: typeof TermsIndexRoute
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiAuthRegisterRoute: typeof ApiAuthRegisterRoute
  authRegisterIndexRoute: typeof authRegisterIndexRoute
  authSigninIndexRoute: typeof authSigninIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms/': {
      id: '/terms/'
      path: '/terms'
      fullPath: '/terms/'
      preLoaderRoute: typeof TermsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/': {
      id: '/templates/'
      path: '/templates'
      fullPath: '/templates/'
      preLoaderRoute: typeof TemplatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support/': {
      id: '/support/'
      path: '/support'
      fullPath: '/support/'
      preLoaderRoute: typeof SupportIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy/': {
      id: '/privacy/'
      path: '/privacy'
      fullPath: '/privacy/'
      preLoaderRoute: typeof PrivacyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mockups/': {
      id: '/mockups/'
      path: '/mockups'
      fullPath: '/mockups/'
      preLoaderRoute: typeof MockupsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/magazines/': {
      id: '/magazines/'
      path: '/magazines'
      fullPath: '/magazines/'
      preLoaderRoute: typeof MagazinesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/license/': {
      id: '/license/'
      path: '/license'
      fullPath: '/license/'
      preLoaderRoute: typeof LicenseIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graphics/': {
      id: '/graphics/'
      path: '/graphics'
      fullPath: '/graphics/'
      preLoaderRoute: typeof GraphicsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/contact/': {
      id: '/contact/'
      path: '/contact'
      fullPath: '/contact/'
      preLoaderRoute: typeof ContactIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/': {
      id: '/about/'
      path: '/about'
      fullPath: '/about/'
      preLoaderRoute: typeof AboutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/$slug': {
      id: '/templates/$slug'
      path: '/templates/$slug'
      fullPath: '/templates/$slug'
      preLoaderRoute: typeof TemplatesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mockups/$slug': {
      id: '/mockups/$slug'
      path: '/mockups/$slug'
      fullPath: '/mockups/$slug'
      preLoaderRoute: typeof MockupsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/magazines/$slug': {
      id: '/magazines/$slug'
      path: '/magazines/$slug'
      fullPath: '/magazines/$slug'
      preLoaderRoute: typeof MagazinesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graphics/$slug': {
      id: '/graphics/$slug'
      path: '/graphics/$slug'
      fullPath: '/graphics/$slug'
      preLoaderRoute: typeof GraphicsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/graphql': {
      id: '/api/graphql'
      path: '/api/graphql'
      fullPath: '/api/graphql'
      preLoaderRoute: typeof ApiGraphqlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/settings/': {
      id: '/dashboard/settings/'
      path: '/settings'
      fullPath: '/dashboard/settings/'
      preLoaderRoute: typeof DashboardSettingsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/purchase_history/': {
      id: '/dashboard/purchase_history/'
      path: '/purchase_history'
      fullPath: '/dashboard/purchase_history/'
      preLoaderRoute: typeof DashboardPurchase_historyIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/profile/': {
      id: '/dashboard/profile/'
      path: '/profile'
      fullPath: '/dashboard/profile/'
      preLoaderRoute: typeof DashboardProfileIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/products/': {
      id: '/dashboard/products/'
      path: '/products'
      fullPath: '/dashboard/products/'
      preLoaderRoute: typeof DashboardProductsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/folders/': {
      id: '/dashboard/folders/'
      path: '/folders'
      fullPath: '/dashboard/folders/'
      preLoaderRoute: typeof DashboardFoldersIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/(auth)/signin/': {
      id: '/(auth)/signin/'
      path: '/signin'
      fullPath: '/signin/'
      preLoaderRoute: typeof authSigninIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/register/': {
      id: '/(auth)/register/'
      path: '/register'
      fullPath: '/register/'
      preLoaderRoute: typeof authRegisterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/register': {
      id: '/api/auth/register'
      path: '/api/auth/register'
      fullPath: '/api/auth/register'
      preLoaderRoute: typeof ApiAuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardFoldersIndexRoute: typeof DashboardFoldersIndexRoute
  DashboardProductsIndexRoute: typeof DashboardProductsIndexRoute
  DashboardProfileIndexRoute: typeof DashboardProfileIndexRoute
  DashboardPurchase_historyIndexRoute: typeof DashboardPurchase_historyIndexRoute
  DashboardSettingsIndexRoute: typeof DashboardSettingsIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardFoldersIndexRoute: DashboardFoldersIndexRoute,
  DashboardProductsIndexRoute: DashboardProductsIndexRoute,
  DashboardProfileIndexRoute: DashboardProfileIndexRoute,
  DashboardPurchase_historyIndexRoute: DashboardPurchase_historyIndexRoute,
  DashboardSettingsIndexRoute: DashboardSettingsIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  ApiGraphqlRoute: ApiGraphqlRoute,
  GraphicsSlugRoute: GraphicsSlugRoute,
  MagazinesSlugRoute: MagazinesSlugRoute,
  MockupsSlugRoute: MockupsSlugRoute,
  TemplatesSlugRoute: TemplatesSlugRoute,
  AboutIndexRoute: AboutIndexRoute,
  ContactIndexRoute: ContactIndexRoute,
  GraphicsIndexRoute: GraphicsIndexRoute,
  LicenseIndexRoute: LicenseIndexRoute,
  MagazinesIndexRoute: MagazinesIndexRoute,
  MockupsIndexRoute: MockupsIndexRoute,
  PrivacyIndexRoute: PrivacyIndexRoute,
  SupportIndexRoute: SupportIndexRoute,
  TemplatesIndexRoute: TemplatesIndexRoute,
  TermsIndexRoute: TermsIndexRoute,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiAuthRegisterRoute: ApiAuthRegisterRoute,
  authRegisterIndexRoute: authRegisterIndexRoute,
  authSigninIndexRoute: authSigninIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
